from django.urls import path

from mailing import views

app_name = "mailing"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("health/", views.health, name="health"),
    path("operator/campaigns/", views.operator_campaign_list, name="operator_campaign_list"),
    path("operator/campaigns/new/", views.operator_campaign_create, name="operator_campaign_create"),
    path("operator/campaigns/<int:campaign_id>/", views.operator_campaign_detail, name="operator_campaign_detail"),
    path("operator/campaigns/<int:campaign_id>/edit/", views.operator_campaign_edit, name="operator_campaign_edit"),
    path("operator/campaigns/<int:campaign_id>/queue/", views.operator_campaign_queue, name="operator_campaign_queue"),
    path("operator/audiences/", views.operator_audience_list, name="operator_audience_list"),
    path("operator/audiences/new/", views.operator_audience_create, name="operator_audience_create"),
    path("operator/audiences/<int:audience_id>/", views.operator_audience_detail, name="operator_audience_detail"),
    path("operator/audiences/<int:audience_id>/edit/", views.operator_audience_edit, name="operator_audience_edit"),
    path("operator/audiences/<int:audience_id>/tags/new/", views.operator_tag_create, name="operator_tag_create"),
    path("operator/tags/<int:tag_id>/", views.operator_tag_detail, name="operator_tag_detail"),
    path("operator/tags/<int:tag_id>/edit/", views.operator_tag_edit, name="operator_tag_edit"),
    path("operator/clients/", views.operator_client_list, name="operator_client_list"),
    path("operator/clients/new/", views.operator_client_create, name="operator_client_create"),
    path("operator/clients/<int:client_id>/", views.operator_client_detail, name="operator_client_detail"),
    path("operator/clients/<int:client_id>/edit/", views.operator_client_edit, name="operator_client_edit"),
    path(
        "operator/clients/<int:client_id>/api-key/generate/",
        views.operator_client_api_key_generate,
        name="operator_client_api_key_generate",
    ),
    path(
        "operator/clients/<int:client_id>/api-key/revoke/",
        views.operator_client_api_key_revoke,
        name="operator_client_api_key_revoke",
    ),
    path("operator/contacts/", views.operator_contact_search, name="operator_contact_search"),
    path("operator/contacts/<int:contact_id>/", views.operator_contact_detail, name="operator_contact_detail"),
    path(
        "operator/contacts/<int:contact_id>/state/",
        views.operator_contact_state_update,
        name="operator_contact_state_update",
    ),
    path(
        "operator/contacts/<int:contact_id>/subscriptions/",
        views.operator_contact_subscription_update,
        name="operator_contact_subscription_update",
    ),
    path("operator/contacts/<int:contact_id>/tags/add/", views.operator_contact_tag_add, name="operator_contact_tag_add"),
    path(
        "operator/contacts/<int:contact_id>/tags/remove/",
        views.operator_contact_tag_remove,
        name="operator_contact_tag_remove",
    ),
    path("operator/api-docs/", views.operator_api_docs, name="operator_api_docs"),
    path("operator/api-docs/openapi.json", views.operator_api_docs_json, name="operator_api_docs_json"),
    path("t/o/<str:tracking_token>.gif", views.tracking_open, name="tracking_open"),
    path("t/c/<str:tracking_token>", views.tracking_click, name="tracking_click"),
    path("unsubscribe/<str:unsubscribe_token>", views.public_unsubscribe, name="public_unsubscribe"),
    path("webhooks/ses", views.ses_webhook, name="ses_webhook"),
    path("api/v1/contacts.csv", views.api_contacts_csv, name="api_contacts_csv"),
    path("api/v1/contacts/imports", views.api_contact_imports, name="api_contact_imports"),
    path("api/v1/contacts/imports/csv", views.api_contact_imports_csv, name="api_contact_imports_csv"),
    path("api/v1/contacts", views.api_contacts, name="api_contacts"),
    path("api/v1/contacts/status", views.api_contact_status, name="api_contact_status"),
    path("api/v1/contacts/<int:contact_id>/tags", views.api_contact_tags, name="api_contact_tags"),
    path("api/v1/contacts/<int:contact_id>/tags/<slug:tag_slug>", views.api_contact_tag, name="api_contact_tag"),
    path(
        "api/v1/contacts/<int:contact_id>/verification",
        views.api_contact_verification,
        name="api_contact_verification",
    ),
    path("api/v1/contacts/<int:contact_id>/validation", views.api_contact_validation, name="api_contact_validation"),
    path("api/v1/contacts/<int:contact_id>/suppression", views.api_contact_suppression, name="api_contact_suppression"),
    path("api/v1/contacts/<int:contact_id>/history", views.api_contact_history, name="api_contact_history"),
    path("api/v1/subscriptions/subscribe", views.api_subscribe, name="api_subscribe"),
    path("api/v1/subscriptions/unsubscribe", views.api_unsubscribe, name="api_unsubscribe"),
    path("api/v1/transactional/send", views.api_transactional_send, name="api_transactional_send"),
]
