# Generated by Django 6.0.5 on 2026-05-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=320)),
                ('normalized_email', models.EmailField(max_length=320, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('global_unsubscribed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hard_bounced_at', models.DateTimeField(blank=True, null=True)),
                ('complained_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['normalized_email'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('api_key_hash', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='mailing.organization')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['organization__slug', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='mailing.organization')),
            ],
            options={
                'db_table': 'audiences',
                'ordering': ['organization__slug', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.CharField(blank=True, max_length=255)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='mailing.audience')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='mailing.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='mailing.contact')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['audience__slug', 'client__slug', 'contact__normalized_email'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='mailing.audience')),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['audience__slug', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='mailing.contact')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='mailing.tag')),
            ],
            options={
                'db_table': 'contact_tags',
                'ordering': ['tag__audience__slug', 'tag__slug', 'contact__normalized_email'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(related_name='contacts', through='mailing.ContactTag', to='mailing.tag'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='clients_is_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_client_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='audience',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_audience_slug_per_organization'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['audience', 'client', 'status'], name='subs_aud_cli_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['contact', 'updated_at'], name='subs_contact_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('contact', 'audience', 'client'), name='unique_subscription_scope'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True)), fields=('contact', 'audience'), name='unique_audience_only_subscription_scope'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('audience', 'slug'), name='unique_tag_slug_per_audience'),
        ),
        migrations.AddIndex(
            model_name='contacttag',
            index=models.Index(fields=['tag', 'contact'], name='contact_tags_tag_contact_idx'),
        ),
        migrations.AddConstraint(
            model_name='contacttag',
            constraint=models.UniqueConstraint(fields=('contact', 'tag'), name='unique_contact_tag'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['hard_bounced_at'], name='contacts_hard_bounced_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['complained_at'], name='contacts_complained_idx'),
        ),
    ]
