# Generated by Django 6.0.5 on 2026-05-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('preview_text', models.CharField(blank=True, max_length=255)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('snapshotting', 'Snapshotting'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('include_tags', models.JSONField(blank=True, default=list)),
                ('exclude_tags', models.JSONField(blank=True, default=list)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('unique_open_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('unique_click_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('unsubscribe_count', models.PositiveIntegerField(default=0)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('complaint_count', models.PositiveIntegerField(default=0)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='mailing.audience')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='mailing.client')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=320)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('skip_reason', models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('global_unsubscribe', 'Global unsubscribe'), ('client_unsubscribe', 'Client unsubscribe'), ('audience_unsubscribe', 'Audience unsubscribe'), ('hard_bounce', 'Hard bounce'), ('complaint', 'Complaint'), ('duplicate', 'Duplicate'), ('suppressed', 'Suppressed')], max_length=30)),
                ('tracking_token_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('unsubscribe_token_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ses_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_clicked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mailing.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_recipients', to='mailing.contact')),
            ],
            options={
                'db_table': 'campaign_recipients',
                'ordering': ['campaign_id', 'contact__normalized_email'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['client', 'audience', 'status'], name='campaign_client_aud_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['scheduled_at'], name='campaign_scheduled_at_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='campaign_recip_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['contact', 'sent_at'], name='camp_recip_contact_sent_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact'), name='unique_campaign_recipient_contact'),
        ),
    ]
