# Generated by Django 6.0.5 on 2026-05-24 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_campaign_campaignrecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('is_transactional', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_templates', to='mailing.client')),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['client__slug', 'key'],
            },
        ),
        migrations.CreateModel(
            name='TransactionalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=320)),
                ('template_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='queued', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('ses_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactional_messages', to='mailing.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactional_messages', to='mailing.contact')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactional_messages', to='mailing.emailtemplate')),
            ],
            options={
                'db_table': 'transactional_messages',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('skipped', 'Skipped'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('open', 'Open'), ('click', 'Click'), ('unsubscribe', 'Unsubscribe'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('failed', 'Failed')], max_length=20)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_events', to='mailing.audience')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mailing.campaign')),
                ('campaign_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mailing.campaignrecipient')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_events', to='mailing.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_events', to='mailing.contact')),
                ('transactional_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mailing.transactionalmessage')),
            ],
            options={
                'db_table': 'email_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['client', 'is_transactional'], name='email_tpl_client_tx_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('client', 'key'), name='unique_email_template_client_key'),
        ),
        migrations.AddIndex(
            model_name='transactionalmessage',
            index=models.Index(fields=['contact', 'created_at'], name='tx_msg_contact_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionalmessage',
            index=models.Index(fields=['client', 'status', 'created_at'], name='tx_msg_cli_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionalmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('client', 'idempotency_key'), name='unique_transactional_client_idempotency'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['contact', 'created_at'], name='email_evt_contact_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['campaign', 'event_type', 'created_at'], name='email_events_campaign_type_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['campaign_recipient', 'event_type'], name='email_evt_recipient_type_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['client', 'created_at'], name='email_evt_client_created_idx'),
        ),
    ]
