# Generated by Django 6.0.5 on 2026-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_emailevent_provider_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_validated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_validation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_validation_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('invalid_syntax', 'Invalid syntax'), ('no_mx', 'No MX'), ('disposable', 'Disposable'), ('risky', 'Risky'), ('manually_invalid', 'Manually invalid'), ('externally_validated', 'Externally validated')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('invalid_email', 'Invalid email'), ('global_unsubscribe', 'Global unsubscribe'), ('client_unsubscribe', 'Client unsubscribe'), ('audience_unsubscribe', 'Audience unsubscribe'), ('hard_bounce', 'Hard bounce'), ('complaint', 'Complaint'), ('duplicate', 'Duplicate'), ('suppressed', 'Suppressed')], max_length=30),
        ),
    ]
