# Generated by Django 6.0.5 on 2026-05-24 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_contact_email_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('target_type', models.CharField(db_index=True, max_length=80)),
                ('target_id', models.PositiveBigIntegerField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_audits',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'target_id', 'created_at'], name='op_audit_target_created_idx'), models.Index(fields=['actor', 'created_at'], name='op_audit_actor_created_idx')],
            },
        ),
    ]
