# Generated by Django 6.0.5 on 2026-05-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_operator_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSourceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_source_metadata', to='mailing.audience')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_source_metadata', to='mailing.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_metadata', to='mailing.contact')),
            ],
            options={
                'db_table': 'contact_source_metadata',
                'ordering': ['source', 'contact__normalized_email'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='contact_src_ext_idx'), models.Index(fields=['audience', 'client', 'source'], name='contact_src_scope_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'audience', 'client', 'source'), name='unique_contact_source_metadata_scope')],
            },
        ),
    ]
