# Generated by Django 6.0.5 on 2026-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_contact_source_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='example_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='required_context',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['client', 'is_transactional', 'is_active'], name='email_tpl_tx_active_idx'),
        ),
    ]
