# Generated by Django 6.0.5 on 2026-05-25 09:10

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def migrate_client_api_keys(apps, schema_editor):
    Client = apps.get_model("mailing", "Client")
    ClientApiKey = apps.get_model("mailing", "ClientApiKey")
    now = timezone.now()
    for client in Client.objects.exclude(api_key_hash=""):
        ClientApiKey.objects.create(
            client_id=client.id,
            name="Migrated key",
            key_hash=client.api_key_hash,
            public_id=f"legacy{client.id}",
            notes="Migrated from the pre-multiple-key client credential.",
            created_at=now,
            updated_at=now,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_transactional_template_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('key_hash', models.CharField(max_length=255)),
                ('public_id', models.CharField(max_length=32, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='mailing.client')),
            ],
            options={
                'db_table': 'client_api_keys',
                'ordering': ['client__organization__slug', 'client__slug', 'revoked_at', 'name'],
                'indexes': [models.Index(fields=['public_id'], name='client_api_keys_public_id_idx'), models.Index(fields=['client', 'revoked_at'], name='client_api_keys_client_state_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('client', 'name'), name='unique_active_api_key_name_per_client')],
            },
        ),
        migrations.RunPython(migrate_client_api_keys, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='client',
            name='api_key_hash',
        ),
    ]
