# Generated by Django 6.0.5 on 2026-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_multiple_client_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allowed_from_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='default_from_email',
            field=models.EmailField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='transactionalmessage',
            name='from_email',
            field=models.EmailField(blank=True, max_length=320),
        ),
    ]
