# Generated by Django 6.0.5 on 2026-06-16 14:31

from django.db import migrations, models
from django.utils.text import slugify


def sender_id_from_email(email):
    sender_id = slugify(str(email).split("@", 1)[0])
    return sender_id or "sender"


def populate_sender_ids(apps, schema_editor):
    Client = apps.get_model("mailing", "Client")
    TransactionalMessage = apps.get_model("mailing", "TransactionalMessage")

    for client in Client.objects.all():
        configured = []
        seen_ids = set()
        for email in [client.default_from_email, *(client.allowed_from_emails or [])]:
            email = str(email or "").strip()
            if not email:
                continue
            base_id = sender_id_from_email(email)
            sender_id = base_id
            index = 2
            while sender_id in seen_ids:
                sender_id = f"{base_id}-{index}"
                index += 1
            configured.append({"id": sender_id, "email": email})
            seen_ids.add(sender_id)

        default_sender_id = ""
        if client.default_from_email:
            for sender in configured:
                if sender["email"] == client.default_from_email:
                    default_sender_id = sender["id"]
                    break
        elif configured:
            default_sender_id = configured[0]["id"]

        client.sender_emails = configured
        client.default_sender_id = default_sender_id
        client.save(update_fields=["sender_emails", "default_sender_id"])

        if default_sender_id:
            TransactionalMessage.objects.filter(client=client, from_email_id="").update(from_email_id=default_sender_id)


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_client_allowed_from_emails_client_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_sender_id',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='sender_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transactionalmessage',
            name='from_email_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(populate_sender_ids, migrations.RunPython.noop),
    ]
