# Generated by Django 6.0.5 on 2026-06-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_client_default_sender_id_client_sender_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('registrants', 'Registrants'), ('homework_submitters', 'Homework submitters'), ('project_submitters', 'Project submitters'), ('custom', 'Custom')], default='custom', max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('active_member_count', models.PositiveIntegerField(default=0)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_lists', to='mailing.audience')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_lists', to='mailing.client')),
            ],
            options={
                'db_table': 'recipient_lists',
                'ordering': ['client__slug', 'audience__slug', 'key'],
            },
        ),
        migrations.CreateModel(
            name='RecipientListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=320)),
                ('source_object_key', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_list_members', to='mailing.contact')),
                ('recipient_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='mailing.recipientlist')),
            ],
            options={
                'db_table': 'recipient_list_members',
                'ordering': ['recipient_list_id', 'source_object_key'],
            },
        ),
        migrations.AddIndex(
            model_name='recipientlist',
            index=models.Index(fields=['client', 'audience', 'type'], name='recip_list_scope_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipientlist',
            constraint=models.UniqueConstraint(fields=('client', 'audience', 'key'), name='unique_recipient_list_scope_key'),
        ),
        migrations.AddIndex(
            model_name='recipientlistmember',
            index=models.Index(fields=['recipient_list', 'active'], name='recip_list_member_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipientlistmember',
            constraint=models.UniqueConstraint(fields=('recipient_list', 'contact'), name='unique_recipient_list_contact'),
        ),
        migrations.AddConstraint(
            model_name='recipientlistmember',
            constraint=models.UniqueConstraint(fields=('recipient_list', 'source_object_key'), name='unique_recipient_list_source_object'),
        ),
    ]
