# Generated by Django 6.0.5 on 2026-06-19 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_recipientlist_recipientlistmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cmp_webhook_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='cmp_webhook_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='emailevent',
            name='event_type',
            field=models.CharField(choices=[('queued', 'Queued'), ('skipped', 'Skipped'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('open', 'Open'), ('click', 'Click'), ('subscribe', 'Subscribe'), ('unsubscribe', 'Unsubscribe'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.CreateModel(
            name='CmpCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('callback_url', models.URLField(max_length=2048)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmp_callbacks', to='mailing.audience')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmp_callbacks', to='mailing.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmp_callbacks', to='mailing.contact')),
                ('email_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cmp_callback', to='mailing.emailevent')),
            ],
            options={
                'db_table': 'cmp_callbacks',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='cmp_cb_status_next_idx'), models.Index(fields=['client', 'status', 'created_at'], name='cmp_cb_client_status_idx')],
            },
        ),
    ]
