# Generated by Django 6.0.5 on 2026-06-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0013_client_cmp_webhook_token_client_cmp_webhook_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionalmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("bounced", "Bounced"),
                    ("complained", "Complained"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
