# Generated by Django 6.0.5 on 2026-06-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_alter_transactionalmessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.SlugField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_reason', models.CharField(blank=True, max_length=255)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to='mailing.audience')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to='mailing.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to='mailing.contact')),
            ],
            options={
                'db_table': 'category_preferences',
                'ordering': ['client__slug', 'audience__slug', 'contact__normalized_email', 'tag'],
                'indexes': [models.Index(fields=['client', 'audience', 'tag', 'enabled'], name='cat_pref_scope_tag_enabled_idx'), models.Index(fields=['contact', 'client', 'audience'], name='cat_pref_contact_scope_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'audience', 'client', 'tag'), name='unique_category_preference_scope')],
            },
        ),
    ]
