# Generated by Codex on 2026-06-26

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0015_categorypreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="external_key",
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                condition=~Q(external_key=""),
                fields=("client", "external_key"),
                name="unique_campaign_external_key_per_client",
            ),
        ),
    ]
