# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0016_campaign_external_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapturedEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=320)),
                ("from_email", models.CharField(blank=True, max_length=320)),
                ("subject", models.CharField(max_length=255)),
                ("html_body", models.TextField(blank=True)),
                ("text_body", models.TextField(blank=True)),
                ("template_key", models.CharField(blank=True, max_length=120)),
                ("source", models.CharField(db_index=True, max_length=80)),
                ("event", models.CharField(blank=True, db_index=True, max_length=120)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "audience",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_emails",
                        to="mailing.audience",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captured_emails",
                        to="mailing.campaign",
                    ),
                ),
                (
                    "campaign_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captured_emails",
                        to="mailing.campaignrecipient",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captured_emails",
                        to="mailing.client",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_emails",
                        to="mailing.contact",
                    ),
                ),
                (
                    "transactional_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captured_emails",
                        to="mailing.transactionalmessage",
                    ),
                ),
            ],
            options={
                "db_table": "captured_emails",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="capturedemail",
            index=models.Index(fields=["client", "created_at"], name="capt_email_client_created_idx"),
        ),
        migrations.AddIndex(
            model_name="capturedemail",
            index=models.Index(fields=["client", "email", "created_at"], name="capt_email_client_email_idx"),
        ),
        migrations.AddIndex(
            model_name="capturedemail",
            index=models.Index(fields=["client", "source", "created_at"], name="capt_email_client_source_idx"),
        ),
        migrations.AddIndex(
            model_name="capturedemail",
            index=models.Index(fields=["client", "event", "created_at"], name="capt_email_client_event_idx"),
        ),
    ]
