# Generated by Django 6.0.5 on 2026-06-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_capturedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='default_sender_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
