# Generated by Django 6.0.5 on 2026-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0018_emailtemplate_default_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category_tag',
            field=models.SlugField(blank=True, max_length=80),
        ),
    ]
