# Generated by Django 6.0.5 on 2026-06-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0019_campaign_category_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
