# Generated by Django 6.0.5 on 2026-06-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0020_campaign_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='recipient_list_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
