# Generated by Django 6.0.5 on 2026-06-26 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0021_campaign_recipient_list_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientListImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_key', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=2048)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('list_defaults', models.JSONField(blank=True, default=dict)),
                ('remove_absent', models.BooleanField(default=False)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('removed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.JSONField(blank=True, default=list)),
                ('content_sha256', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_list_import_jobs', to='mailing.audience')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_list_import_jobs', to='mailing.client')),
                ('recipient_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='mailing.recipientlist')),
            ],
            options={
                'db_table': 'recipient_list_import_jobs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['client', 'audience', 'status'], name='recip_import_scope_status_idx'), models.Index(fields=['list_key', 'created_at'], name='recip_import_list_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('client', 'idempotency_key'), name='unique_recipient_list_import_job_idempotency')],
            },
        ),
    ]
