# Generated by Django 6.0.5 on 2026-07-03 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0022_recipientlistimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mailchimp_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='mailchimp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='mailchimp_list_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='MailchimpSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=320)),
                ('list_key', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=200)),
                ('mailchimp_list_id', models.CharField(max_length=64)),
                ('dedup_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mailchimp_syncs', to='mailing.audience')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailchimp_syncs', to='mailing.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mailchimp_syncs', to='mailing.contact')),
            ],
            options={
                'db_table': 'mailchimp_syncs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='mc_sync_status_next_idx'), models.Index(fields=['client', 'status', 'created_at'], name='mc_sync_client_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='MailchimpTagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_key', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailchimp_tag_mappings', to='mailing.audience')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailchimp_tag_mappings', to='mailing.client')),
            ],
            options={
                'db_table': 'mailchimp_tag_mappings',
                'ordering': ['client__slug', 'audience__slug', 'list_key', 'tag'],
                'indexes': [models.Index(fields=['client', 'audience', 'list_key'], name='mc_tag_map_scope_key_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'audience', 'list_key', 'tag'), name='unique_mailchimp_tag_mapping')],
            },
        ),
    ]
