# Generated by Django 6.0.5 on 2026-07-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0023_client_mailchimp_api_key_client_mailchimp_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='capturedemail',
            name='capt_email_client_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='capturedemail',
            name='capt_email_client_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='capturedemail',
            name='capt_email_client_source_idx',
        ),
        migrations.RemoveIndex(
            model_name='capturedemail',
            name='capt_email_client_event_idx',
        ),
        migrations.DeleteModel(
            name='CapturedEmail',
        ),
    ]
